server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enable: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/spring-boot-real-dev/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9090/realms/spring-boot-real-dev/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9090/realms/spring-boot-real-dev/protocol/openid-connect/token
        registration:
          spring-client-api-rest:
            provider: keycloak
            client-id: spring-client-api-rest
            client-secret: tOeFhVmrBMdRKpMmJOy6xXedPOiCIX1u
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/*"

